name: Check for X Team review

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check if team approved
        uses: joaomdmoura/actiontest@v0.2
        with:
          reviews: ${{ github.event.pull_request.reviews }}
          team: '["@joaomdmoura"]'
